services:
  web-frontend:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html  # This is the magic fix!

  database-storage:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - luvo-db-vault:/var/lib/postgresql

volumes:
  luvo-db-vault:
