services:
  reverse-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - lamigo-frontend

  lamigo-frontend:
    image: nginx:latest
    # This is the exact fix. It opens the internal door.
    expose:
      - "80"
    volumes:
      - ./frontend:/usr/share/nginx/html

  database-storage:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - luvo-db-vault:/var/lib/postgresql

volumes:
  luvo-db-vault:
