services:
  # 1. The Armed Security Receptionist (Nginx + Certbot)
  reverse-proxy:
    image: jonasal/nginx-certbot:latest
    environment:
      # You MUST use a real email here for the certificate authority
      - CERTBOT_EMAIL=chanul26.mac@gmail.com
    ports:
      - "80:80"   # Open for verification
      - "443:443" # Open for secure HTTPS traffic!
    volumes:
      - ./nginx/default.conf:/etc/nginx/user_conf.d/default.conf
      - letsencrypt-keys:/etc/letsencrypt
    depends_on:
      - lamigo-frontend

  # 2. The Internal Website
  lamigo-frontend:
    image: nginx:latest
    expose:
      - "80"
    volumes:
      - ./frontend:/usr/share/nginx/html

  # 3. The Database Vault
  database-storage:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - luvo-db-vault:/var/lib/postgresql

volumes:
  luvo-db-vault:
  letsencrypt-keys: # The vault where the encryption keys will be stored
