server {
    # Listen on Port 443 for Secure Traffic
    listen 443 ssl;
    server_name lamigo.13.212.176.249.nip.io;

    # Certbot will automatically place the keys here!
    ssl_certificate /etc/letsencrypt/live/lamigo.13.212.176.249.nip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lamigo.13.212.176.249.nip.io/privkey.pem;

    location / {
        proxy_pass http://lamigo-frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
    }
}
