# Routing for LamiGo
server {
    listen 80;
    server_name lamigo.13.212.176.249.nip.io;

    location / {
        # We tell Nginx to forward this traffic to the web-frontend container
        proxy_pass http://web-frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# Routing for LUVO Clothing (Simulated 2nd app for now)
server {
    listen 80;
    server_name luvo.13.212.176.249.nip.io;

    location / {
        # If we had a luvo container, it would point there. 
        # For this lab, we will return a simple text response to prove it works!
        default_type text/html;
        return 200 "<h1>Welcome to LUVO Clothing (Routed via Nginx Reverse Proxy!)</h1>";
    }
}
