# Routing for LamiGo
server {
    listen 80;
    server_name lamigo.13.212.176.249.nip.io;

    location / {
        # Notice we changed the destination to the new hidden container!
        proxy_pass http://lamigo-frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# Routing for LUVO
server {
    listen 80;
    server_name luvo.13.212.176.249.nip.io;

    location / {
        default_type text/html;
        return 200 "<h1>Welcome to LUVO Clothing (Routed via Nginx Reverse Proxy!)</h1>";
    }
}
