name: Chanul CI/CD Test Pipeline

# The Trigger: Wake up on every push
on:
  push:
    branches:
      - main
      - master

# The Work: What the robot does
jobs:
  test-the-robot:
    # We tell GitHub to rent a free, temporary Ubuntu server to run our script
    runs-on: ubuntu-latest 
    
    steps:
      - name: Print a success message
        run: echo "Hello Chanul! The CI/CD Pipeline is alive and working perfectly!"
