name: Auto-Deployment Pipeline with CI

on:
  push:
    branches:
      - main

jobs:
  # ========================================
  # STAGE 1: THE CI SCANNER (Testing)
  # ========================================
  test-the-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run HTML Validation Test
        run: |
          if grep -q "<h1>" frontend/index.html; then
            echo "Test Passed: Valid H1 tag found."
            exit 0
          else
            echo "Test Failed: Missing H1 tag!"
            exit 1
          fi

  # ========================================
  # STAGE 2: THE CD DEPLOYMENT
  # ========================================
  deploy-to-aws:
    needs: test-the-code
    runs-on: ubuntu-latest

    steps:
      - name: Securely Login and Update Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/compose-lab/
            git pull origin main
            sudo docker compose up -d --build --remove-orphans
