name: Chanul Auto-Deployment Pipeline

# 1. The Trigger
on:
  push:
    branches:
      - main

# 2. The Robot's Instructions
jobs:
  deploy-to-aws:
    runs-on: ubuntu-latest
    
    steps:
      - name: Securely Login and Update Server
        # We use a pre-built GitHub Action module designed specifically for SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          # The robot pulls the keys directly from your GitHub Secrets Vault
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          # This is exactly what the robot types into your AWS terminal!
          script: |
            cd /home/ubuntu/compose-lab/
            git pull origin main
            sudo docker compose up -d --build
